# Generated by Django 5.2.7 on 2026-04-03 15:24

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short description for cards and meta tags",
                    ),
                ),
                ("body", models.TextField(help_text="Markdown content")),
                ("date", models.DateField(help_text="Original publication date")),
                ("updated", models.DateField(blank=True, null=True)),
                ("author", models.CharField(default="Dennis Loevlie", max_length=100)),
                (
                    "medium_url",
                    models.URLField(
                        blank=True,
                        help_text="Canonical URL if originally published elsewhere",
                    ),
                ),
                ("draft", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
