# Generated by Django 5.2.7 on 2026-04-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="Static path for cover image, e.g. portfolio/images/blog/cover.jpg",
                max_length=300,
            ),
        ),
    ]
