# Generated by Django 5.2.7 on 2026-04-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="series",
            field=models.CharField(
                blank=True,
                help_text="Series name, e.g. 'Deep Dive: Multiple Instance Learning'",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="series_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order within the series (1, 2, 3...)"
            ),
        ),
    ]
