# Generated by Django 5.2.7 on 2026-04-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_post_series_post_series_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_explainer",
            field=models.BooleanField(
                default=False,
                help_text="Render with explainer chrome: Tufte sidenotes, hover citations, BibTeX export, wider figure canvas.",
            ),
        ),
    ]
