# Generated by Django 5.2.7 on 2026-04-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_post_is_explainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="maturity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unmarked"),
                    ("seedling", "Seedling — half-formed"),
                    ("budding", "Budding — being developed"),
                    ("evergreen", "Evergreen — settled"),
                ],
                default="",
                help_text="Optional digital-garden maturity badge. Sets reader expectations and lets unfinished thinking ship without 'blog-post-as-final-statement' cost.",
                max_length=12,
            ),
        ),
    ]
