# Generated by Django 5.2.7 on 2026-04-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_post_maturity"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_paper_companion",
            field=models.BooleanField(
                default=False,
                help_text="Render as a magazine-grade companion essay (Asterisk / Works in Progress register): single column, large serif body, drop cap, real footnotes at bottom, pull-quotes. Use for paper-companion essays where the prose is the artifact.",
            ),
        ),
    ]
