# Generated by Django 5.2.7 on 2026-04-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_post_is_paper_companion"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySalt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("salt", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Pageview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("path", models.CharField(db_index=True, max_length=500)),
                ("referrer", models.CharField(blank=True, max_length=500)),
                ("country", models.CharField(blank=True, db_index=True, max_length=2)),
                ("device", models.CharField(blank=True, db_index=True, max_length=16)),
                ("browser", models.CharField(blank=True, max_length=32)),
                ("viewport_w", models.PositiveSmallIntegerField(default=0)),
                ("viewport_h", models.PositiveSmallIntegerField(default=0)),
                ("session_id", models.CharField(db_index=True, max_length=32)),
                ("ip_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("is_bot", models.BooleanField(db_index=True, default=False)),
                ("scroll_depth", models.PositiveSmallIntegerField(default=0)),
                ("dwell_ms", models.PositiveIntegerField(default=0)),
                (
                    "post_slug",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at", "path"],
                        name="portfolio_p_created_521235_idx",
                    ),
                    models.Index(
                        fields=["created_at", "session_id"],
                        name="portfolio_p_created_b1ca4f_idx",
                    ),
                ],
            },
        ),
    ]
