# Generated by Django 5.2.7 on 2026-04-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_dailysalt_pageview"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="rendered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="rendered_html",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="post",
            name="rendered_toc_html",
            field=models.TextField(blank=True, default=""),
        ),
    ]
