# Generated by Django 5.2.7 on 2026-04-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_post_rendered_at_post_rendered_html_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "venue",
                    models.CharField(
                        blank=True,
                        help_text="Where it was published — arXiv id, conference, journal, magazine, etc.",
                        max_length=200,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Canonical link (arXiv, blog post, etc.)"
                    ),
                ),
                (
                    "annotation",
                    models.TextField(
                        blank=True,
                        help_text="One-line note in your own voice — what makes it interesting to you right now.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("this_week", "This week — actively reading"),
                            ("chewing", "Older but still chewing on"),
                            ("archived", "Archived (hidden from /reading/)"),
                        ],
                        default="this_week",
                        max_length=16,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Lower = higher in the list within its status bucket. Ties broken by created_at desc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reading entry",
                "verbose_name_plural": "Reading entries",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="kind",
            field=models.CharField(
                choices=[
                    ("essay", "Essay (long-form, /blog/)"),
                    ("lab_note", "Lab note (open log, /notebook/)"),
                ],
                default="essay",
                help_text="Which surface this post belongs to. Essays go to /blog/; lab notes go to /notebook/. Garden is orthogonal.",
                max_length=16,
            ),
        ),
    ]
