# Generated by Django 5.2.7 on 2026-04-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_seed_reading"),
    ]

    operations = [
        migrations.AddField(
            model_name="reading",
            name="mind_mapper_note_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
