# Generated by Django 5.2.7 on 2026-04-21 02:23

from django.db import migrations, models


def chewing_to_lingering(apps, schema_editor):
    """Update any existing Reading rows whose status is the old
    'chewing' value to the new 'lingering' value. Reverse maps
    'lingering' back to 'chewing' so a downgrade is non-destructive."""
    Reading = apps.get_model("portfolio", "Reading")
    Reading.objects.filter(status="chewing").update(status="lingering")


def lingering_to_chewing(apps, schema_editor):
    Reading = apps.get_model("portfolio", "Reading")
    Reading.objects.filter(status="lingering").update(status="chewing")


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_reading_mind_mapper_note_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="status",
            field=models.CharField(
                choices=[
                    ("this_week", "This week — actively reading"),
                    ("lingering", "Older but still lingering"),
                    ("archived", "Archived (hidden from /reading/)"),
                ],
                default="this_week",
                max_length=16,
            ),
        ),
        migrations.RunPython(chewing_to_lingering, reverse_code=lingering_to_chewing),
    ]
