# Generated by Django 5.2.7 on 2026-04-21 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_rename_chewing_to_lingering"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        help_text="Display string, e.g. '2026' or 'Apr 2026'. Stored as string so you can write '2026 —' or 'Spring 2025'.",
                        max_length=40,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="HTML allowed. Kept short: one bullet's worth."
                    ),
                ),
                (
                    "highlight",
                    models.BooleanField(
                        default=False,
                        help_text="Render with the accent left-rule treatment for top items.",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Lower = higher in the list."
                    ),
                ),
                (
                    "draft",
                    models.BooleanField(
                        default=False, help_text="Hidden from the public homepage."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "News item",
                "verbose_name_plural": "News items",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NowPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated",
                    models.DateField(
                        help_text="Displayed on the page so readers know how stale it is."
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                ("draft", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Now page",
                "verbose_name_plural": "Now page",
            },
        ),
        migrations.CreateModel(
            name="OpenSourceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("url", models.URLField()),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Contributor', 'Maintainer'.",
                        max_length=80,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("draft", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Open-source contribution",
                "verbose_name_plural": "Open-source contributions",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="One-paragraph summary; 2–4 sentences is the sweet spot."
                    ),
                ),
                (
                    "tags_csv",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags shown as chips, e.g. 'LLM, Optimization, PyTorch'.",
                        max_length=300,
                    ),
                ),
                (
                    "github",
                    models.CharField(
                        blank=True,
                        help_text="GitHub slug, e.g. 'loevlie/neuropt'. Used for star-count badge.",
                        max_length=200,
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=40)),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="Surface in the top 6 on /#projects (above the 'Show more' fold).",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Lower = higher in the list."
                    ),
                ),
                ("draft", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "-modified_at"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "authors",
                    models.CharField(
                        help_text="Comma-separated author list. Use the author's name as you'd like it shown.",
                        max_length=500,
                    ),
                ),
                ("venue", models.CharField(blank=True, max_length=300)),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "pub_type",
                    models.CharField(
                        choices=[
                            ("conference", "Conference paper"),
                            ("journal", "Journal article"),
                            ("poster", "Poster"),
                            ("preprint", "Preprint"),
                            ("thesis", "Thesis"),
                            ("workshop", "Workshop paper"),
                        ],
                        default="conference",
                        help_text="Drives the 'Conference'/'Journal'/'Poster' pill on publication cards.",
                        max_length=24,
                    ),
                ),
                (
                    "selected",
                    models.BooleanField(
                        default=False,
                        help_text="Promote to the homepage Selected Publications block.",
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        help_text="Static-files path, e.g. 'portfolio/images/cover_acr.jpeg'. Required when selected=True.",
                        max_length=400,
                    ),
                ),
                ("image_credit", models.CharField(blank=True, max_length=300)),
                ("bibtex", models.TextField(blank=True)),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Lower = higher in the list."
                    ),
                ),
                (
                    "draft",
                    models.BooleanField(
                        default=False, help_text="Hidden from public pages."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "-year"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "url",
                    models.CharField(
                        help_text="Full URL or mailto: link.", max_length=400
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("scholar", "Google Scholar"),
                            ("linkedin", "LinkedIn"),
                            ("bluesky", "Bluesky"),
                            ("medium", "Medium"),
                            ("twitter", "Twitter / X"),
                            ("email", "Email"),
                        ],
                        max_length=24,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("draft", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TimelineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        help_text="Display range, e.g. '2026 —' or '2021 — 2023'.",
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("org", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("link", models.URLField(blank=True)),
                ("link_label", models.CharField(blank=True, max_length=80)),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Lower = higher; newest first."
                    ),
                ),
                ("draft", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Timeline entry",
                "verbose_name_plural": "Timeline entries",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NowSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=100)),
                (
                    "body",
                    models.TextField(
                        help_text="Markdown allowed — rendered at view time."
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "now_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_set",
                        to="portfolio.nowpage",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. 'Code', 'Demo', 'Paper'.", max_length=40
                    ),
                ),
                ("url", models.URLField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_set",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PublicationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. 'Paper', 'Code', 'Poster'.", max_length=40
                    ),
                ),
                ("url", models.URLField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_set",
                        to="portfolio.publication",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
