# Generated by Django 5.2.7 on 2026-04-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0013_newsitem_nowpage_opensourceitem_project_publication_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reading",
            name="mm_annotation",
            field=models.TextField(
                blank=True,
                help_text="Optional annotation sourced from a matched Mind Mapper note. Shown beneath your own annotation on /reading/. Overwritten on every `sync_reading` run; edit in Mind Mapper, not here.",
            ),
        ),
    ]
