# Generated by Django 5.2.7 on 2026-04-23 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_reading_mm_annotation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Non-staff users who can edit this specific post.",
                related_name="edit_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
