# Generated by Django 5.2.7 on 2026-04-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_post_collaborators"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="notation",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
