# Generated by Django 5.2.7 on 2026-04-23 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0020_author_inline_backfill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users in the byline (one row = one credited author, with a position).",
                related_name="edit_posts",
                through="portfolio.PostCollaborator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
