# Generated by Django 5.2.7 on 2026-04-23 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0021_alter_post_collaborators"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text='Slug used by <cite data-key="...">. Convention: firstauthor + year + shortword (e.g. vaswani2017attention).',
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                (
                    "authors",
                    models.CharField(
                        help_text='Display string, e.g. "E. Harvey, D. Loevlie, M. Hughes".',
                        max_length=400,
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True,
                        help_text='Journal / conference / "arXiv preprint".',
                        max_length=200,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
                ("bibtex", models.TextField(blank=True)),
                (
                    "arxiv_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="If this was auto-fetched from arXiv, the bare id (e.g. 2510.25759). Used to dedupe — a second paste of the same arXiv URL reuses this row.",
                        max_length=40,
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="If this was auto-fetched from CrossRef, the DOI (e.g. 10.1021/acs.accounts.2c00646).",
                        max_length=120,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Citation",
                "verbose_name_plural": "Citations",
                "ordering": ["-year", "key"],
            },
        ),
    ]
