# Generated by Django 5.2.7 on 2026-04-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0022_citation"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Cover image shown on the post header + listings. Upload via the editor.",
                null=True,
                upload_to="blog_covers/",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="Legacy: static path for cover image. Use the uploaded `cover_image` instead.",
                max_length=300,
            ),
        ),
    ]
