# Generated by Django 5.2.7 on 2026-06-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0023_post_cover_image_alter_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportedPostLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
