# Generated by Django 5.2.7 on 2026-06-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0024_importedpostledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug_is_auto",
            field=models.BooleanField(default=False),
        ),
    ]
